CREATE TABLE IF NOT EXISTS STUDENT(
ROLL_NO INTEGER PRIMARY KEY,
NAME VARCHAR(20),
CITY VARCHAR(20),
MARKS REAL,
AGE INTEGER
);

INSERT INTO STUDENT (ROLL_NO, NAME, CITY, MARKS, AGE) VALUES
(1, 'Alice', 'New York', 85.5,18),
(2, 'Bob', 'Los Angeles', 78.0,19),
(3, 'Charlie', 'Chicago', 92.0,18),
(4, 'David', 'Houston', 88.5,19),
(5, 'Eve', 'Phoenix', 91.0,18);

SELECT * FROM STUDENT
WHERE AGE=18 AND CITY='New York';

SELECT * FROM STUDENT
WHERE NAME='Alice' AND AGE=18;
